# .streamlit/secrets.toml

[mongo]
host = "mongodb://localhost"
port = 27017

[mongodb]
db_name = "ECG"
collection_ecg_name = "ecg"
collection_channel_name = "channel"
collection_record_set_name = "recordSet"
collection_template_exportation_name = "templateExportation"

[configure]
format_descriptor = "WFDB;SciPy"
channel_name = "I;II;III;aVR;aVL;aVF;V1;V2;V3;V4;V5;V6;Vx;Vy;Vz"